import type { NextPage } from 'next';
import Head from 'next/head';
import NavBar from '../components/common/nav-bar';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Print on demand</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
      </main>
    </div>
  );
};

export default Home;
