import NavBar from "@/components/common/nav-bar";
import { LayoutProps } from "@/models/index";
import { useRouter } from "next/router";
import * as React from "react";
import { useAppSelector } from "../hooks/reduxHook";

export interface IMainLayoutProps {}

export function MainLayout({ children }: LayoutProps) {
  const auth = useAppSelector((state) => state.auth);
  const router = useRouter();
  if (auth.roleName !== "ADMIN" && auth.roleName !== "FACTORY") {
    router.push("/login");
  }
  return (
    <div>
      {/* <Head>
        <title>Print on demand</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className="layout-wrapper">
        <div className="layout-container">
          <NavBar />
          <div className="layout-page">
            <div className="content-wrapper">
              <div>{children}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
