import NavBar from "@/components/common/nav-bar";
import { LayoutProps } from "@/models/index";
import * as React from "react";

export interface IMainLayoutProps {}

export function MainLayout({ children }: LayoutProps) {
  return (
    <div>
      {/* <Head>
        <title>Print on demand</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className="layout-wrapper">
        <div className="layout-container">
          <NavBar />
          <div className="layout-page">
            <div className="content-wrapper">
              <div>{children}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
